import type { Metadata } from "next";

import "./globals.css";
import localFont from "next/font/local";

const tobiasFont = localFont({
  variable: "--font-body",
  src: "./fonts/TobiasRegular.woff2",
})

const tobiasLightFont = localFont({
  variable: "--font-body-light",
  src: "./fonts/TobiasLight.woff2",
})

const PPEditorialFont = localFont({
  variable: "--font-title",
  src: "./fonts/PPEditorial.woff2",
})

const PPEditorialFontItalic = localFont({
  variable: "--font-title-italic",
  src: "./fonts/PPEditorialItalic.woff2",
})

const PPEditorialFontLight = localFont({
  variable: "--font-title-light",
  src: "./fonts/PPEditorialLight.woff2",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${tobiasFont.variable} ${PPEditorialFont.variable} ${PPEditorialFontItalic.variable} ${PPEditorialFontLight.variable} ${tobiasLightFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
